### ISSUE TITLE
Creazione Header

### ISSUE THREAD

**Issue by AkasakaRyuunoske** [AkasakaRyuunoske/tempest-double#24]
Scrivere il componente header che puo essere semplicemente importato in ogni pagina HTML e che sia responsive, in particolare serve:

- [x]  rendere visibile il menu quando il dispositivo ha una certa dimensione
- [x]  rendere nav responsive
- [x]  mettere link nel header per le altre pagine.
- [x]  rendere header un componente importabile (magari tramite Thymeleaf)
- [x]  mettere header nelle altre pagine

**Comment by cay3na** [comment]
¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by cay3na** [comment]
header done, font not working, maybe add animations, maybe fix font doesnt enlarge on small screen

**Comment by cay3na** [comment]
what "metter header in altre pagine"? if altre pagine doesnt exist yet

**Comment by cay3na** [comment]
no menu anymore

**Comment by AkasakaRyuunoske** [comment]
> what "metter header in altre pagine"? if altre pagine doesnt exist yet

le sta faccendo il tuo collega max alessandro. A presto verano mergiate (se non sono gia mergiate, controlla stato del branch con pull)

**Comment by cay3na** [comment]
- [x] text enlarges on small screens

**Comment by cay3na** [comment]
- [x] add menu when screen is becoming smaller
