### ISSUE TITLE
Pagina dello storico

### ISSUE THREAD

**Issue by AkasakaRyuunoske** [AkasakaRyuunoske/tempest-double#29]
Creare un componente base, con dati hard-coded per contenere righe con lo storico delle simulazioni seguendo quanto progettato.

**Comment by cay3na** [comment]
Proposte per migliorare.
Sono disponibile per chiarimenti. 
Se hai domande o suggerimenti, non esitare a chiedere.

- [x] tradurre i nomi dei class in inglese 
- [x] usare rem unit invece di px unit in css
- [x] rinominare script.js per history in "history.js"
- [x] scrivere solo i html che riguarda history page in "history.html"
- [x] scrivere solo i css che riguarda history page in "history.css"
- [x] scrivere solo i js che riguarda history page in "history.js"
- [x] spostare dichiarazione script alla fine del body 
- [x] aggiungere checkbox per selezionare tutti i scenari
- [x] aggiungere button delete per eliminare scenario selezionato/i
- [x] aggiungere checkbox per selezionare il scenario (dentro il card content sopra class="data-ora")
- [x] cambiare color di border-bottom di "session-card h3" con #455271
