### ISSUE TITLE
Creazione pagina Simulazione (Base)

### ISSUE THREAD

**Issue by AkasakaRyuunoske** [AkasakaRyuunoske/tempest-double#35]
Creare la pagina di simulazione seguendo quanto progettato. Per ora la pagina deve contenere dati hard-coded, ci interessa solo la struttura.

Da fare:

- [x] Creare il template per la pagina.
- [x] Creare css necessario. (Mi aspetto piu css considerando la difficolta della pagina)
- [x] Creare js necessario.
- [x] Pagina deve essere responsive.

**Comment by cay3na** [comment]
Broke

**Comment by AkasakaRyuunoske** [comment]
Chiuso in pr #45
