### ISSUE TITLE
Bug Fix #1: Problemini di merge

### ISSUE THREAD

**Issue by AkasakaRyuunoske** [AkasakaRyuunoske/tempest-double#39]
Risolvere tutti i problemi che sono apparsi nel merge gigante delle due issue. Nel commento di questa issue scrivere gli fix effettuati.

**Comment by AkasakaRyuunoske** [comment]
- [x] Mettere i stili .css che si usano in piu pagine in un singolo .css che puo essere genericamente chiamato "styles.css" e mettere nella cartella /static/css.
- [x] Fare una cosa simile per JS. Quello che viene riusato in piu pagine (come animazione di slide per esempio) mettere in un singolo .js condiviso da piu pagine. Metere questo file nella cartella /static/js

**Comment by cay3na** [comment]
Need Review.
Suggestions to improve?
Finished.

**Comment by AkasakaRyuunoske** [comment]
chiusa in PR #45.
