### ISSUE TITLE
Pagina Assets and Topologies: Aggiungere pop up per ogni pulsante

### ISSUE THREAD

**Issue by AkasakaRyuunoske** [AkasakaRyuunoske/tempest-double#71]
Creare pop-up con le logiche necessarie per ogni pulsante presente nella pagina di Assets and Topologiess:

@alemassim0 
Aggiungere pop up per Pulsanti (Senza alcuna logica):
- [x] Add
- [x] Delete
- [x] Save
- [x] Load

@AkasakaRyuunoske 
Aggiungere logica per ogni pop up:
- [x] Add
- [x] Delete
- [x] Save
- [x] Load

![image](https://github.com/user-attachments/assets/ba8724c3-0172-4f30-9760-3bc577367b67)

**Comment by alemassim0** [comment]
l'unico problema che mi sembra più evidente è che al momento se si clicca su add viene aggiunto un nuovo nodo indipendentemente dalla caratteristiche scelte dall'utente.
